pipeline:

  publish_latest:
    image: plugins/docker
    repo: arbetsformedlingen/gig-web
    secrets: [ docker_username, docker_password, react_app_google_maps_api_key, react_app_api_host ]
    force_tag: true
    tags: latest
    build_args_from_env:
      - REACT_APP_GOOGLE_MAPS_API_KEY
      - REACT_APP_API_HOST
    when:
      branch: master
      event: push

  publish_tag:
    image: plugins/docker
    repo: arbetsformedlingen/gig-web
    secrets: [ docker_username, docker_password, react_app_google_maps_api_key, react_app_api_host ]
    force_tag: true
    tags:
      - ${DRONE_TAG##v}
    build_args_from_env:
      - REACT_APP_GOOGLE_MAPS_API_KEY
      - REACT_APP_API_HOST
    when:
      status: success
      event: tag
